### PR TITLE
Try: Add quick setup settings for gateway recommendations

### PR DESCRIPTION
**Pull request by joshuatf**
This PR is for testing purposes.  

This is part of the new remote recommended payment gateways feature.  Related PR - https://github.com/woocommerce/woocommerce-admin/pull/7025

### CODE REVIEW

**Review by psealock — APPROVED** [review]
Tested as part of https://github.com/woocommerce/woocommerce-admin/pull/7025 and confirmed its working well.

**Comment by tubiz** [comment]
Thanks, @joshuatf. I will also test and have it merged.

**Comment by tubiz** [comment]
@joshuatf I noticed you submitted another PR, #64 for this. Can I close that?

**Comment by tubiz** [comment]
Closing in favor of #64

**Pull request closed without merging**
